[package]
name = "google-domains-ddns-rust"
version = "0.1.0"
authors = ["WarossK <mail@sasaki.games>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.3"
curl = "0.4.29"
